services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=logistics_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_IST: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api-gateway

  api-gateway:
    build: ./services/api-gateway
    environment:
      - PORT=3000
      - JWT_SECRET=supersecret
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  order-service:
    build: ./services/order-service
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/logistics_db
      - RABBIT_URL=amqp://rabbitmq
      - JWT_SECRET=supersecret
      - INVOICE_GENERATOR_URL=https://us-central1-maximal-airfoil-484219-n9.cloudfunctions.net/generateInvoice
    depends_on:
      - postgres
      - rabbitmq

  tracking-service:
    build: ./services/tracking-service
    environment:
      - KAFKA_BROKER=kafka:9092
      - JWT_SECRET=supersecret
    depends_on:
      - kafka

  invoice-generator:
    build: ./functions/invoice-generator
    ports:
      - "8080:8080"

  app-host:
    build: ./apps/host
    ports:
      - "5000:5000"
    depends_on:
      - nginx
      
  app-dashboard:
    build: ./apps/dashboard
    ports:
      - "5001:5001"
      
  app-tracking:
    build: ./apps/tracking
    ports:
      - "5002:5002"